"""Make user_id optional in conversations for anonymous users

Revision ID: dcfc9be4cb42
Revises: 7e327c825394
Create Date: 2025-11-05 18:23:06.820952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcfc9be4cb42'
down_revision: Union[str, None] = 'c6b4f57b71ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('conversations_user_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_user_id_fkey'), 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('conversations', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
